AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation templates to create checks for common security mistakes in the account. https://github.com/awslabs/aws-security-assessment-solution/
Parameters:
  InstanceRoleARN:
    Type: String
  SelfServiceSecS3Bucket:
    Type: String
  TemplatesS3Bucket:
    Type: String
Conditions:
  CreateGovCloudResources: !Equals [ !Ref "AWS::Partition", aws ]

Resources:
  rLambdaCheckForCommonMistakes:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !Ref TemplatesS3Bucket
        S3Key: "modules/CommonSecurityMistakes/cosp.zip"
      FunctionName: "LambdaCheckForCommonMistakes"
      Handler: "cosp"
      MemorySize: 256
      Role: !Ref InstanceRoleARN
      Runtime: "go1.x"
      Timeout: 900
      DeadLetterConfig: !Ref "AWS::NoValue"
      TracingConfig:
        Mode: "PassThrough"
      Environment:
        Variables:
          reportbucket: !Ref SelfServiceSecS3Bucket

  xLambdaCheckForCommonMistakes:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt rLambdaCheckForCommonMistakes.Arn